on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build
        run: |
          npm install -g pnpm
          pnpm install
          pnpm lint
          pnpm build
          pnpm test
