on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build portfolio
        working-directory: ./portfolio
        run: |
          yarn install
          yarn build
          
      - name: Build AWS
        working-directory: ./aws
        run: |
          npm ci
          npm run lint
          npm run test
          npm run cdk synth
