on: push

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with: 
          aws-region: us-east-1
          role-to-assume: ${{ secrets.ROLE_ARN }}

      - name: Build portfolio
        working-directory: ./portfolio
        run: |
          yarn install
          yarn build
          
      - name: Build AWS
        working-directory: ./aws
        run: |
          npm ci
          npm run lint
          npm run test

      - name: Diff
        working-directory: ./aws
        run: npx cdk diff -c accountId=${{ secrets.ACCOUNT_ID }}

      - name: Deploy
        working-directory: ./aws
        if: ${{ github.ref == 'refs/heads/main' }}
        run: npx cdk deploy -c accountId=${{ secrets.ACCOUNT_ID }} --require-approval never
