on: push

jobs:
  build-portfolio:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./portfolio
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build
        run: |
          yarn install
          yarn build
          
  build-aws:
    runs-on: ubuntu-latest
    needs: build-portfolio
    defaults:
      run:
        working-directory: ./aws
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build
        run: |
          npm ci
          npm run lint
          npm run test
          npm run cdk synth
